@startuml
skin rose
hide empty members

entity Restaurante {
Nombre
Direccion
}

entity Trabajador {
Nombre
Edad
Tipo de contrato
Fecha de contratacion
}

entity Orden {
Trabajador Asignado
Producto
Cantidad
Resumen
Cuenta
}

entity Mesa {
{static}Numero
Posicion
Disponibilidad
Registro
}

entity Cliente {
Nombre
Edad
}

entity Inventario {
Nombre del producto
Precio
Categoria
Stock
}

Restaurante -left-> Inventario : Gestiona >
Restaurante "1" <-right- "0..*" Cliente : Ingresa <
Restaurante "1" -down-> "1..*" Trabajador : Administra >
Trabajador "0.." -right-> "1" Orden : Atiende >
Orden "1" -up-> "0, 1" Mesa : Asociada >
Mesa "1" <-up- "0..*" Cliente : Reserva <
Cliente "1" -left-> "1" Orden : Genera >
@enduml