@startuml
skin rose
hide empty members

entity Restaurante {
Nombre
Direccion
}

entity Trabajador {
Nombre
Edad
Tipo de contrato
Fecha de contratacion
}

entity Orden {
Trabajador
Producto
Resumen
Cuenta
}

entity Mesa {
Disponibilidad
Registro
}

entity Cliente {
Nombre
Edad
}

entity Inventario {
Nombre del producto
Precio
Categoria
Stock
}

Restaurante -left-> Inventario : Gestiona >
Restaurante "1" <-right- "0.." Cliente
Restaurante "1" <-down- "0.." Trabajador : Trabaja <
Trabajador "0.." -right-> "1" Orden : Atiende >
Orden "1" -up-> "0, 1" Mesa : Asociada >
Mesa "1" -up-> "0.." Cliente : Ofrece >
Cliente "1" -left-> "1" Orden : Genera >
@enduml